In [4]:
import pandas as pd

#Data from https://biruni.tuik.gov.tr/bolgeselistatistik/anaSayfa.do?dil=tr

data_TÜİK = pd.read_csv("TÜİK_Agro_Summary.csv",encoding='latin-1')


# Check Turkish Titles
data_TÜİK.columns

Index(['YIL', 'BÖLGE KODU', 'BÖLGE ADI',
       'Tahýllar ve diðer bitkisel ürünlerin hasat edilen alaný (hektar) : Toplam',
       'Tahýllar ve diðer bitkisel ürünlerin üretim miktarý (ton) : Toplam',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu  : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý)',
       'Tarýmsal üretim deðeri  : Bitkisel üretim deðeri  (1000 TL)',
       'Ortalama hanehalký büyüklüðü : Ortalama hanehalký büyüklüðü',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre yaþ grubu ve cinsiyete göre nüfus : Toplam',
       'Örtü altý sebze ve meyve üretimi (ton) : Toplam',
       'Belediye atýk istatistikleri : Kiþi baþý ortalama belediye atýk miktarý (kg/kiþi-gün)',
       'Kullaným yerlerine göre elektrik tüketimi : Toplam (MWh)',
       'Hanehalký tiplerine göre hanehalký sayýsý : Toplam',
       'Niteliklerine göre örtü altý tarým alanlarý (dekar) : Toplam',
       'Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Belediyelerde kiþi baþý çekilen günlük su miktarý (litre/kiþi-gün)',
       'Tarýmsal üretim deðeri  : Canlý hayvanlar deðeri (1000 TL)',
       'Tarýmsal üretim deðeri  : Hayvansal ürünler deðeri (1000 TL)',
       'Alan kullanýmý  : Ýþlenen tarým alaný / Ekilen (hektar)',
       'Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Toplam çekilen su miktarý (1000 m3/yýl)',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu',
       'Alan kullanýmý  : Ýþlenen tarým alaný / Nadas (hektar)',
       'Tarýmsal üretim deðeri  : Kiþi baþýna bitkisel üretim deðeri (TL)',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre yaþ baðýmlýlýk oraný  : Toplam yaþ baðýmlýlýk oraný',
       'Belediye atýk istatistikleri : Toplanan atýk miktarý (1000 ton)',
       'Alan kullanýmý  : Ýþlenen tarým alaný / Sebze (hektar)',
       'Tarýmsal üretim deðeri  : Kiþi baþýna canlý hayvanlar deðeri (TL)',
       'Kullaným yerlerine göre elektrik tüketimi : Tarýmsal faaliyetler (MWh)',
       'Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Toplam arýtýlan içme ve kullanma suyu miktarý (1000 m3/yýl)',
       'Alan kullanýmý  : Toplam uzun ömürlü bitkilerin alaný (hektar)'],
      dtype='object')

In [5]:
# Check invalid variables
data_TÜİK.head(20)

,YIL,BÖLGE KODU,BÖLGE ADI,Tahýllar ve diðer bitkisel ürünlerin hasat edilen alaný (hektar) : Toplam,Tahýllar ve diðer bitkisel ürünlerin üretim miktarý (ton) : Toplam,Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý),Tarýmsal üretim deðeri : Bitkisel üretim deðeri (1000 TL),Ortalama hanehalký büyüklüðü : Ortalama hanehalký büyüklüðü,Adrese Dayalý Nüfus Kayýt Sistemine göre yaþ grubu ve cinsiyete göre nüfus : Toplam,Örtü altý sebze ve meyve üretimi (ton) : Toplam,...,Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu,Alan kullanýmý : Ýþlenen tarým alaný / Nadas (hektar),Tarýmsal üretim deðeri : Kiþi baþýna bitkisel üretim deðeri (TL),Adrese Dayalý Nüfus Kayýt Sistemine göre yaþ baðýmlýlýk oraný : Toplam yaþ baðýmlýlýk oraný,Belediye atýk istatistikleri : Toplanan atýk miktarý (1000 ton),Alan kullanýmý : Ýþlenen tarým alaný / Sebze (hektar),Tarýmsal üretim deðeri : Kiþi baþýna canlý hayvanlar deðeri (TL),Kullaným yerlerine göre elektrik tüketimi : Tarýmsal faaliyetler (MWh),Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Toplam arýtýlan içme ve kullanma suyu miktarý (1000 m3/yýl),Alan kullanýmý : Toplam uzun ömürlü bitkilerin alaný (hektar)
0,2008,TR,Türkiye,15520257,74382684,93,66010114.0,4,71517100,5063265,...,17905377,4259190,923.0,"49,51",24361,835795,357.0,5806475,2120561,2949981
1,2010,TR,Türkiye,16239191,90579900,96,80038126.0,"3,8",73722988,5750466,...,17500632,4249026,1086.0,"48,89",25277,801598,636.0,5585508,2520085,3010580
2,2012,TR,Türkiye,15888286,92921409,98,87946988.0,"3,7",75627384,6170827,...,17178953,4286137,1163.0,"48,03",25845,826736,840.0,5849875,2729430,3200961
3,2014,TR,Türkiye,16057638,99443102,101,98123089.0,"3,6",77695904,6481820,...,6409722,4107618,1263.0,"47,6",28011,803576,805.0,5161403,2995001,3242811
4,2016,TR,Türkiye,15893335,110785755,104,119237661.0,"3,5",79814871,7165241,...,6143123,3998296,1494.0,"47,16",31584,804142,1126.0,6805436,3350389,3329217
5,2018,TR,Türkiye,15782361,115048445,107,159142178.0,"3,4",82003882,8071026,...,6337385,3512773,1941.0,"47,4",32209,783632,1783.0,9278429,3574058,3456910
6,2020,TR,Türkiye,16171078,131927312,109,246016799.0,"3,3",83614362,8519754,...,5878321,3173252,2942.0,"47,75",32324,779246,2335.0,11550108,3900478,3558749
7,2022,TR,Türkiye,17139847,137422726,111,NaN,"3,2",85279553,9329382,...,5666274,2959561,NaN,"46,8",30284,717680,NaN,13427781,4061607,3671409
8,2024,TR,Türkiye,17239720,141261544,111,NaN,"3,1",85664944,8984760,...,5657686,2655434,NaN,"46,12",32279,740686,NaN,NaN,NaN,3799202
9,2008,TR100,Ýstanbul,68391,313740,2444,258569.0,"3,8",12697164,8474,...,128123,-,20.0,"42,1",5215,3831,15.0,94765,612293,2483
10,2010,TR100,Ýstanbul,63991,242510,2551,261585.0,"3,8",13255685,5740,...,135089,108,20.0,"41,69",5731,3867,24.0,72873,812614,2807
11,2012,TR100,Ýstanbul,64766,317338,2666,315623.0,"3,6",13854740,5292,...,144228,498,23.0,"40,84",5671,3711,27.0,27144,930825,2713
12,2014,TR100,Ýstanbul,65711,290051,2767,348883.0,"3,5",14377018,5783,...,-,171,24.0,"40,35",6065,3410,20.0,12821,951497,2663
13,2016,TR100,Ýstanbul,67199,292705,2849,369403.0,"3,5",14804116,4516,...,-,162,25.0,"40,16",7035,2965,35.0,45770,983307,2714
14,2018,TR100,Ýstanbul,66563,300315,2900,483449.0,"3,4",15067724,4820,...,-,156,32.0,"40,44",7043,2937,59.0,63053,1040965,2727
15,2020,TR100,Ýstanbul,67863,302899,2976,629485.0,"3,3",15462452,5681,...,-,611,41.0,"40,41",6959,2870,77.0,52066,1074134,2744
16,2022,TR100,Ýstanbul,70636,327349,3062,NaN,"3,2",15907951,6534,...,-,596,NaN,"39,14",6553,2801,NaN,60906,1103672,2802
17,2024,TR100,Ýstanbul,68470,286601,2934,NaN,"3,1",15701602,7669,...,-,825,NaN,"38,31",7024,2584,NaN,NaN,NaN,2718
18,2008,TR211,Tekirdað,349672,1433099,122,935080.0,"3,5",770772,994,...,249218,-,1213.0,"40,32",372,7193,456.0,13465,2110,9247
19,2010,TR211,Tekirdað,344676,1310936,126,819878.0,"3,5",798109,3527,...,252628,77,1027.0,"40,95",376,5834,722.0,10091,4619,9853

In [6]:
data_TÜİK = data_TÜİK.drop(columns=["Adrese Dayalý Nüfus Kayýt Sistemine göre yaþ baðýmlýlýk oraný  : Toplam yaþ baðýmlýlýk oraný", "Hanehalký tiplerine göre hanehalký sayýsý : Toplam", "BÖLGE KODU"])

In [7]:
data_TÜİK = data_TÜİK.rename(columns={"YIL" : "Year", 
                        "BÖLGE ADI" : "Location_Name",
                        "Adrese Dayalý Nüfus Kayýt Sistemine göre yaþ grubu ve cinsiyete göre nüfus : Toplam" : "Population_Total", 
                        "Tarýmsal üretim deðeri  : Bitkisel üretim deðeri  (1000 TL)" : "Agricultural_Production_1000TL", 
                        "Ortalama hanehalký büyüklüðü : Ortalama hanehalký büyüklüðü" :  "Mean_Household_Size",
                        "Tahýllar ve diðer bitkisel ürünlerin hasat edilen alaný (hektar) : Toplam" : "Landuse_Harvest_Hectare",
                        "Hanehalký tiplerine göre hanehalký sayýsý : Toplam" : "Household_Count_Total",
                        "Niteliklerine göre örtü altý tarým alanlarý (dekar) : Toplam" : "Greenhouse_Agro_LandUse_Decare",
                        "Örtü altý sebze ve meyve üretimi (ton) : Toplam" : "Greenhouse_Agro_Production_Ton",
                        "Tahýllar ve diðer bitkisel ürünlerin üretim miktarý (ton) : Toplam" : "Total_Agricultural_Production_Ton",
                        "Alan kullanýmý  : Ýþlenen tarým alaný / Ekilen (hektar)" : "LandUse_Sowed_Hectare",
                        "Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Toplam çekilen su miktarý (1000 m3/yýl)" : "Water_Drainage_1000m3PerYear",
                        "Alan kullanýmý  : Ýþlenen tarým alaný / Nadas (hektar)": "Agriculture_LandUse_Fallow_Hectare",
                        "Belediye atýk istatistikleri : Toplanan atýk miktarý (1000 ton)" : "Waste_Collected_1000Ton",
                        "Kullaným yerlerine göre elektrik tüketimi : Tarýmsal faaliyetler (MWh)" : "Electric_Energy_Use_MWh",
                        "Alan kullanýmý  : Ýþlenen tarým alaný / Sebze (hektar)" : "Agriculture_LandUse_Vegetables_Hectare",
                        "Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Toplam arýtýlan içme ve kullanma suyu miktarý (1000 m3/yýl)" : "Water_Refined_1000m3PerYear",
                        "Alan kullanýmý  : Toplam uzun ömürlü bitkilerin alaný (hektar)" : "Agriculture_Longterm_Crops_Hectare",
                          })

In [8]:
# Turkish Character Encoding Problem
data_TÜİK["Location_Name"].unique()

array(['Türkiye', 'Ýstanbul', 'Tekirdað', 'Edirne', 'Kýrklareli',
       'Balýkesir', 'Çanakkale', 'Ýzmir', 'Aydýn', 'Denizli', 'Muðla',
       'Manisa', 'Afyonkarahisar', 'Kütahya', 'Uþak', 'Bursa',
       'Eskiþehir', 'Bilecik', 'Kocaeli', 'Sakarya', 'Düzce', 'Bolu',
       'Yalova', 'Ankara', 'Konya', 'Karaman', 'Antalya', 'Isparta',
       'Burdur', 'Adana', 'Mersin', 'Hatay', 'Kahramanmaraþ', 'Osmaniye',
       'Kýrýkkale', 'Aksaray', 'Niðde', 'Nevþehir', 'Kýrþehir', 'Kayseri',
       'Sivas', 'Yozgat', 'Zonguldak', 'Karabük', 'Bartýn', 'Kastamonu',
       'Çankýrý', 'Sinop', 'Samsun', 'Tokat', 'Çorum', 'Amasya',
       'Trabzon', 'Ordu', 'Giresun', 'Rize', 'Artvin', 'Gümüþhane',
       'Erzurum', 'Erzincan', 'Bayburt', 'Aðrý', 'Kars', 'Iðdýr',
       'Ardahan', 'Malatya', 'Elazýð', 'Bingöl', 'Tunceli', 'Van', 'Muþ',
       'Bitlis', 'Hakkari', 'Gaziantep', 'Adýyaman', 'Kilis', 'Þanlýurfa',
       'Diyarbakýr', 'Mardin', 'Batman', 'Þýrnak', 'Siirt'], dtype=object)

In [9]:
# Character Encoding
replacements = {
    'Ý': 'İ',
    'ý': 'ı',
    'ð': 'ğ',
    'þ': 'ş',
    'Þ': 'Ş'
}

data_TÜİK["Location_Name"] = data_TÜİK["Location_Name"].str.translate(str.maketrans(replacements))
data_TÜİK["Location_Name"] = data_TÜİK["Location_Name"].str.capitalize()
data_TÜİK["Location_Name"].unique()

array(['Türkiye', 'İstanbul', 'Tekirdağ', 'Edirne', 'Kırklareli',
       'Balıkesir', 'Çanakkale', 'İzmir', 'Aydın', 'Denizli', 'Muğla',
       'Manisa', 'Afyonkarahisar', 'Kütahya', 'Uşak', 'Bursa',
       'Eskişehir', 'Bilecik', 'Kocaeli', 'Sakarya', 'Düzce', 'Bolu',
       'Yalova', 'Ankara', 'Konya', 'Karaman', 'Antalya', 'Isparta',
       'Burdur', 'Adana', 'Mersin', 'Hatay', 'Kahramanmaraş', 'Osmaniye',
       'Kırıkkale', 'Aksaray', 'Niğde', 'Nevşehir', 'Kırşehir', 'Kayseri',
       'Sivas', 'Yozgat', 'Zonguldak', 'Karabük', 'Bartın', 'Kastamonu',
       'Çankırı', 'Sinop', 'Samsun', 'Tokat', 'Çorum', 'Amasya',
       'Trabzon', 'Ordu', 'Giresun', 'Rize', 'Artvin', 'Gümüşhane',
       'Erzurum', 'Erzincan', 'Bayburt', 'Ağrı', 'Kars', 'Iğdır',
       'Ardahan', 'Malatya', 'Elazığ', 'Bingöl', 'Tunceli', 'Van', 'Muş',
       'Bitlis', 'Hakkari', 'Gaziantep', 'Adıyaman', 'Kilis', 'Şanlıurfa',
       'Diyarbakır', 'Mardin', 'Batman', 'Şırnak', 'Siirt'], dtype=object)

In [10]:
data_TÜİK["Mean_Household_Size"] = data_TÜİK["Mean_Household_Size"].str.replace(',', '.').astype(float)
data_TÜİK = data_TÜİK.replace("-", "0")
data_TÜİK = data_TÜİK.convert_dtypes()
# Force all numeric columns to float64
numeric_cols = data_TÜİK.select_dtypes(include=['number']).columns
data_TÜİK[numeric_cols] = data_TÜİK[numeric_cols].astype('float64')
data_TÜİK["Year"] = data_TÜİK["Year"].astype("int64")
data_TÜİK.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 26 columns):
 #   Column                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                  --------------  -----
 0   Year                                                                                                                                    738 non-null    int64
 1   Location_Name                                                                                                                           738 non-null    string
 2   Landuse_Harvest_Hectare                                                                                                                 738 non-null    float64
 3   Total_Agricultural_Production_Ton                                                                                                       738 non-null    float64
 4   Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu  : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý)                         738 non-null    float64
 5   Agricultural_Production_1000TL                                                                                                          574 non-null    float64
 6   Mean_Household_Size                                                                                                                     738 non-null    float64
 7   Population_Total                                                                                                                        738 non-null    float64
 8   Greenhouse_Agro_Production_Ton                                                                                                          738 non-null    string
 9   Belediye atýk istatistikleri : Kiþi baþý ortalama belediye atýk miktarý (kg/kiþi-gün)                                                   738 non-null    string
 10  Kullaným yerlerine göre elektrik tüketimi : Toplam (MWh)                                                                                656 non-null    float64
 11  Greenhouse_Agro_LandUse_Decare                                                                                                          738 non-null    string
 12  Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Belediyelerde kiþi baþý çekilen günlük su miktarý (litre/kiþi-gün)                 656 non-null    float64
 13  Tarýmsal üretim deðeri  : Canlý hayvanlar deðeri (1000 TL)                                                                              574 non-null    float64
 14  Tarýmsal üretim deðeri  : Hayvansal ürünler deðeri (1000 TL)                                                                            574 non-null    float64
 15  LandUse_Sowed_Hectare                                                                                                                   738 non-null    float64
 16  Water_Drainage_1000m3PerYear                                                                                                            656 non-null    float64
 17  Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu  738 non-null    string
 18  Agriculture_LandUse_Fallow_Hectare                                                                                                      738 non-null    string
 19  Tarýmsal üretim deðeri  : Kiþi baþýna bitkisel üretim deðeri (TL)                                                                       574 non-null    float64
 20  Waste_Collected_1000Ton                                                                                                                 738 non-null    float64
 21  Agriculture_LandUse_Vegetables_Hectare                                                                                                  738 non-null    string
 22  Tarýmsal üretim deðeri  : Kiþi baþýna canlý hayvanlar deðeri (TL)                                                                       574 non-null    float64
 23  Electric_Energy_Use_MWh                                                                                                                 656 non-null    string
 24  Water_Refined_1000m3PerYear                                                                                                             656 non-null    string
 25  Agriculture_Longterm_Crops_Hectare                                                                                                      738 non-null    float64
dtypes: float64(16), int64(1), string(9)
memory usage: 150.0 KB

In [11]:
data_TÜİK["Greenhouse_Agro_LandUse_Decare"] = data_TÜİK["Greenhouse_Agro_LandUse_Decare"].astype(float)
data_TÜİK["Greenhouse_Agro_Production_Ton"] = data_TÜİK["Greenhouse_Agro_Production_Ton"].astype(float)
data_TÜİK["Agriculture_LandUse_Fallow_Hectare"] = data_TÜİK["Agriculture_LandUse_Fallow_Hectare"].astype(float)
data_TÜİK["Electric_Energy_Use_MWh"] = data_TÜİK["Electric_Energy_Use_MWh"].astype(float)
data_TÜİK["Agriculture_LandUse_Vegetables_Hectare"] = data_TÜİK["Agriculture_LandUse_Vegetables_Hectare"].astype(float)
data_TÜİK["Water_Refined_1000m3PerYear"] = data_TÜİK["Water_Refined_1000m3PerYear"].astype(float)
data_TÜİK.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 26 columns):
 #   Column                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                  --------------  -----
 0   Year                                                                                                                                    738 non-null    int64
 1   Location_Name                                                                                                                           738 non-null    string
 2   Landuse_Harvest_Hectare                                                                                                                 738 non-null    float64
 3   Total_Agricultural_Production_Ton                                                                                                       738 non-null    float64
 4   Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu  : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý)                         738 non-null    float64
 5   Agricultural_Production_1000TL                                                                                                          574 non-null    float64
 6   Mean_Household_Size                                                                                                                     738 non-null    float64
 7   Population_Total                                                                                                                        738 non-null    float64
 8   Greenhouse_Agro_Production_Ton                                                                                                          738 non-null    float64
 9   Belediye atýk istatistikleri : Kiþi baþý ortalama belediye atýk miktarý (kg/kiþi-gün)                                                   738 non-null    string
 10  Kullaným yerlerine göre elektrik tüketimi : Toplam (MWh)                                                                                656 non-null    float64
 11  Greenhouse_Agro_LandUse_Decare                                                                                                          738 non-null    float64
 12  Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Belediyelerde kiþi baþý çekilen günlük su miktarý (litre/kiþi-gün)                 656 non-null    float64
 13  Tarýmsal üretim deðeri  : Canlý hayvanlar deðeri (1000 TL)                                                                              574 non-null    float64
 14  Tarýmsal üretim deðeri  : Hayvansal ürünler deðeri (1000 TL)                                                                            574 non-null    float64
 15  LandUse_Sowed_Hectare                                                                                                                   738 non-null    float64
 16  Water_Drainage_1000m3PerYear                                                                                                            656 non-null    float64
 17  Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu  738 non-null    string
 18  Agriculture_LandUse_Fallow_Hectare                                                                                                      738 non-null    float64
 19  Tarýmsal üretim deðeri  : Kiþi baþýna bitkisel üretim deðeri (TL)                                                                       574 non-null    float64
 20  Waste_Collected_1000Ton                                                                                                                 738 non-null    float64
 21  Agriculture_LandUse_Vegetables_Hectare                                                                                                  738 non-null    float64
 22  Tarýmsal üretim deðeri  : Kiþi baþýna canlý hayvanlar deðeri (TL)                                                                       574 non-null    float64
 23  Electric_Energy_Use_MWh                                                                                                                 656 non-null    float64
 24  Water_Refined_1000m3PerYear                                                                                                             656 non-null    float64
 25  Agriculture_Longterm_Crops_Hectare                                                                                                      738 non-null    float64
dtypes: float64(22), int64(1), string(3)
memory usage: 150.0 KB

In [12]:
data_TÜİK.head(10)

,Year,Location_Name,Landuse_Harvest_Hectare,Total_Agricultural_Production_Ton,Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý),Agricultural_Production_1000TL,Mean_Household_Size,Population_Total,Greenhouse_Agro_Production_Ton,Belediye atýk istatistikleri : Kiþi baþý ortalama belediye atýk miktarý (kg/kiþi-gün),...,Water_Drainage_1000m3PerYear,Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu,Agriculture_LandUse_Fallow_Hectare,Tarýmsal üretim deðeri : Kiþi baþýna bitkisel üretim deðeri (TL),Waste_Collected_1000Ton,Agriculture_LandUse_Vegetables_Hectare,Tarýmsal üretim deðeri : Kiþi baþýna canlý hayvanlar deðeri (TL),Electric_Energy_Use_MWh,Water_Refined_1000m3PerYear,Agriculture_Longterm_Crops_Hectare
0,2008,Türkiye,15520257.0,74382684.0,93.0,66010114.0,4.0,71517100.0,5063265.0,"1,15",...,4546574.0,17905377,4259190.0,923.0,24361.0,835795.0,357.0,5806475.0,2120561.0,2949981.0
1,2010,Türkiye,16239191.0,90579900.0,96.0,80038126.0,3.8,73722988.0,5750466.0,"1,14",...,4784734.0,17500632,4249026.0,1086.0,25277.0,801598.0,636.0,5585508.0,2520085.0,3010580.0
2,2012,Türkiye,15888286.0,92921409.0,98.0,87946988.0,3.7,75627384.0,6170827.0,"1,12",...,4936342.0,17178953,4286137.0,1163.0,25845.0,826736.0,840.0,5849875.0,2729430.0,3200961.0
3,2014,Türkiye,16057638.0,99443102.0,101.0,98123089.0,3.6,77695904.0,6481820.0,"1,08",...,5237407.0,6409722,4107618.0,1263.0,28011.0,803576.0,805.0,5161403.0,2995001.0,3242811.0
4,2016,Türkiye,15893335.0,110785755.0,104.0,119237661.0,3.5,79814871.0,7165241.0,"1,17",...,5838561.0,6143123,3998296.0,1494.0,31584.0,804142.0,1126.0,6805436.0,3350389.0,3329217.0
5,2018,Türkiye,15782361.0,115048445.0,107.0,159142178.0,3.4,82003882.0,8071026.0,"1,16",...,6193158.0,6337385,3512773.0,1941.0,32209.0,783632.0,1783.0,9278429.0,3574058.0,3456910.0
6,2020,Türkiye,16171078.0,131927312.0,109.0,246016799.0,3.3,83614362.0,8519754.0,"1,13",...,6492402.0,5878321,3173252.0,2942.0,32324.0,779246.0,2335.0,11550108.0,3900478.0,3558749.0
7,2022,Türkiye,17139847.0,137422726.0,111.0,NaN,3.2,85279553.0,9329382.0,"1,03",...,6676197.0,5666274,2959561.0,NaN,30284.0,717680.0,NaN,13427781.0,4061607.0,3671409.0
8,2024,Türkiye,17239720.0,141261544.0,111.0,NaN,3.1,85664944.0,8984760.0,"1,09",...,NaN,5657686,2655434.0,NaN,32279.0,740686.0,NaN,NaN,NaN,3799202.0
9,2008,İstanbul,68391.0,313740.0,2444.0,258569.0,3.8,12697164.0,8474.0,"1,15",...,666000.0,128123,0.0,20.0,5215.0,3831.0,15.0,94765.0,612293.0,2483.0

In [13]:
# Data from https://www.harita.gov.tr/il-ve-ilce-yuzolcumleri

data_HGM = pd.read_excel("Türkiye_Municipal_Areas.xlsx")
data_HGM.head(10)

,İL VE İLÇE YÜZ ÖLÇÜMLERİ,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,AÇIKLAMA: Aşağıda verilen yüz ölçümleri; 2014 ...,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,İL / İLÇE,ALAN (km²)
4,NaN,NaN,ADANA,13844
5,1,1.0,ALADAĞ,1340
6,2,2.0,CEYHAN,1426
7,3,3.0,ÇUKUROVA,250
8,4,4.0,FEKE,1218
9,5,5.0,İMAMOĞLU,445

In [14]:
# Deleting town area values, keeping only city area values

data_HGM = data_HGM[
    data_HGM["İL VE İLÇE YÜZ ÖLÇÜMLERİ"].isna() &
    data_HGM["Unnamed: 1"].isna() &
    data_HGM["Unnamed: 2"].notna()]

data_HGM.reset_index(inplace=True, drop=True)
print(data_HGM)

   İL VE İLÇE YÜZ ÖLÇÜMLERİ  Unnamed: 1      Unnamed: 2  Unnamed: 3
0                       NaN         NaN       İL / İLÇE  ALAN (km²)
1                       NaN         NaN           ADANA       13844
2                       NaN         NaN        ADIYAMAN        7337
3                       NaN         NaN  AFYONKARAHİSAR       14016
4                       NaN         NaN            AĞRI       11099
..                      ...         ...             ...         ...
77                      NaN         NaN            UŞAK        5555
78                      NaN         NaN             VAN       20921
79                      NaN         NaN          YALOVA         798
80                      NaN         NaN          YOZGAT       13690
81                      NaN         NaN       ZONGULDAK        3342

[82 rows x 4 columns]

In [15]:
import unicodedata

# Correction of city name values for Türkiye-HGM data

data_HGM = data_HGM.rename(columns={"Unnamed: 2" : "Location_Name", 
                        "Unnamed: 3" : "Area_km2"})

data_HGM = data_HGM.drop(columns=["İL VE İLÇE YÜZ ÖLÇÜMLERİ", "Unnamed: 1"])
data_HGM.drop(index=0, axis=0, inplace=True)
data_HGM.reset_index(inplace=True, drop=True)


# Capitalize city names while preserving Turkish encoding
def normalize_turkish(text):
    if not isinstance(text, str):
        return text
    # Normalize Unicode composition (fixes dotted İ etc.)
    text = unicodedata.normalize("NFKC", text.strip())
    # Replace locale-specific characters before capitalization
    text = text.translate(str.maketrans("IİŞĞÜÇÖ", "ıişğüçö")).capitalize()
    return text

# Apply to city names
data_HGM["Location_Name"] = data_HGM["Location_Name"].apply(normalize_turkish)


print(data_HGM["Location_Name"].unique())
# For Hakkari, İstanbul, and İzmir
data_HGM["Location_Name"] = data_HGM["Location_Name"].str.replace("Hakkâri", "Hakkari")
data_HGM["Location_Name"] = data_HGM["Location_Name"].str.replace("Istanbul", "İstanbul")
data_HGM["Location_Name"] = data_HGM["Location_Name"].str.replace("Izmir", "İzmir")
print(data_HGM["Location_Name"].unique())

['Adana' 'Adıyaman' 'Afyonkarahisar' 'Ağrı' 'Aksaray' 'Amasya' 'Ankara'
 'Antalya' 'Ardahan' 'Artvin' 'Aydın' 'Balıkesir' 'Bartın' 'Batman'
 'Bayburt' 'Bilecik' 'Bingöl' 'Bitlis' 'Bolu' 'Burdur' 'Bursa' 'Çanakkale'
 'Çankırı' 'Çorum' 'Denizli' 'Diyarbakır' 'Düzce' 'Edirne' 'Elazığ'
 'Erzincan' 'Erzurum' 'Eskişehir' 'Gaziantep' 'Giresun' 'Gümüşhane'
 'Hakkâri' 'Hatay' 'Iğdır' 'Isparta' 'Istanbul' 'Izmir' 'Kahramanmaraş'
 'Karabük' 'Karaman' 'Kars' 'Kastamonu' 'Kayseri' 'Kırıkkale' 'Kırklareli'
 'Kırşehir' 'Kilis' 'Kocaeli' 'Konya' 'Kütahya' 'Malatya' 'Manisa'
 'Mardin' 'Mersin' 'Muğla' 'Muş' 'Nevşehir' 'Niğde' 'Ordu' 'Osmaniye'
 'Rize' 'Sakarya' 'Samsun' 'Siirt' 'Sinop' 'Sivas' 'Şanlıurfa' 'Şırnak'
 'Tekirdağ' 'Tokat' 'Trabzon' 'Tunceli' 'Uşak' 'Van' 'Yalova' 'Yozgat'
 'Zonguldak']
['Adana' 'Adıyaman' 'Afyonkarahisar' 'Ağrı' 'Aksaray' 'Amasya' 'Ankara'
 'Antalya' 'Ardahan' 'Artvin' 'Aydın' 'Balıkesir' 'Bartın' 'Batman'
 'Bayburt' 'Bilecik' 'Bingöl' 'Bitlis' 'Bolu' 'Burdur' 'Bursa' 'Çanakkale'
 'Çankırı' 'Çorum' 'Denizli' 'Diyarbakır' 'Düzce' 'Edirne' 'Elazığ'
 'Erzincan' 'Erzurum' 'Eskişehir' 'Gaziantep' 'Giresun' 'Gümüşhane'
 'Hakkari' 'Hatay' 'Iğdır' 'Isparta' 'İstanbul' 'İzmir' 'Kahramanmaraş'
 'Karabük' 'Karaman' 'Kars' 'Kastamonu' 'Kayseri' 'Kırıkkale' 'Kırklareli'
 'Kırşehir' 'Kilis' 'Kocaeli' 'Konya' 'Kütahya' 'Malatya' 'Manisa'
 'Mardin' 'Mersin' 'Muğla' 'Muş' 'Nevşehir' 'Niğde' 'Ordu' 'Osmaniye'
 'Rize' 'Sakarya' 'Samsun' 'Siirt' 'Sinop' 'Sivas' 'Şanlıurfa' 'Şırnak'
 'Tekirdağ' 'Tokat' 'Trabzon' 'Tunceli' 'Uşak' 'Van' 'Yalova' 'Yozgat'
 'Zonguldak']

In [16]:
data_official_Türkiye = data_TÜİK.merge(
    data_HGM.assign(Location_lower=data_HGM["Location_Name"].str.lower())[["Location_lower", "Area_km2"]],
    left_on=data_TÜİK["Location_Name"].str.lower(),
    right_on="Location_lower",
    how="left"
).drop(columns="Location_lower")
data_official_Türkiye["Area_km2"] = data_official_Türkiye["Area_km2"].astype("float64")

In [17]:
# Control empty area values

missing_area = data_official_Türkiye[data_official_Türkiye["Area_km2"].isna()]
print(missing_area["Location_Name"].unique())

# Because that I replaced the city encodings, only Türkiye was left, picked a reference year 2008 

total_area = data_official_Türkiye.loc[
    (data_official_Türkiye["Year"] == 2008) & (data_official_Türkiye["Location_Name"] != "Türkiye"), "Area_km2"].sum()

# Assign total to Türkiye
data_official_Türkiye.loc[data_official_Türkiye["Location_Name"] == "Türkiye", "Area_km2"] = total_area

missing_area = data_official_Türkiye[data_official_Türkiye["Area_km2"].isna()]
print(missing_area["Location_Name"].unique())

<StringArray>
['Türkiye']
Length: 1, dtype: string
<StringArray>
[]
Length: 0, dtype: string

In [18]:
law6360_cities = ["Aydın", "Balıkesir", "Denizli", "Hatay", "Malatya", "Manisa", "Mardin", "Muğla", "Kahramanmaraş", "Ordu", "Tekirdağ", "Trabzon", "Şanlıurfa", "Van"]
data_official_Türkiye["Treated"] = data_official_Türkiye["Location_Name"].isin(law6360_cities).astype(int)
data_official_Türkiye.columns

Index(['Year', 'Location_Name', 'Landuse_Harvest_Hectare',
       'Total_Agricultural_Production_Ton',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu  : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý)',
       'Agricultural_Production_1000TL', 'Mean_Household_Size',
       'Population_Total', 'Greenhouse_Agro_Production_Ton',
       'Belediye atýk istatistikleri : Kiþi baþý ortalama belediye atýk miktarý (kg/kiþi-gün)',
       'Kullaným yerlerine göre elektrik tüketimi : Toplam (MWh)',
       'Greenhouse_Agro_LandUse_Decare',
       'Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Belediyelerde kiþi baþý çekilen günlük su miktarý (litre/kiþi-gün)',
       'Tarýmsal üretim deðeri  : Canlý hayvanlar deðeri (1000 TL)',
       'Tarýmsal üretim deðeri  : Hayvansal ürünler deðeri (1000 TL)',
       'LandUse_Sowed_Hectare', 'Water_Drainage_1000m3PerYear',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu',
       'Agriculture_LandUse_Fallow_Hectare',
       'Tarýmsal üretim deðeri  : Kiþi baþýna bitkisel üretim deðeri (TL)',
       'Waste_Collected_1000Ton', 'Agriculture_LandUse_Vegetables_Hectare',
       'Tarýmsal üretim deðeri  : Kiþi baþýna canlý hayvanlar deðeri (TL)',
       'Electric_Energy_Use_MWh', 'Water_Refined_1000m3PerYear',
       'Agriculture_Longterm_Crops_Hectare', 'Area_km2', 'Treated'],
      dtype='object')

In [19]:
# Transformations

# Household number and city are will be denominators for food sovereignty analysis.
# Exchange rates for USD/TRY taken from National Bank of the Republic of Türkiye with mean of sale and offer. 
# Exchange rates https://www.tcmb.gov.tr/kurlar/kurlar_tr.html

data_exchangerates = pd.DataFrame({
    'Year': [2008, 2010, 2012, 2014, 2016, 2018],
    'Exchange_Parity_USDTRY': [1.5245, 1.5413, 1.7819, 2.329, 3.5223, 5.2857]})

data_official_Türkiye = data_official_Türkiye.merge(
    data_exchangerates, on="Year", how="left")


data_official_Türkiye["Mean_Household_Count"] = data_official_Türkiye["Population_Total"] / data_official_Türkiye["Mean_Household_Size"]
data_official_Türkiye["Landuse_Harvest_km2"] = data_official_Türkiye["Landuse_Harvest_Hectare"] * 0.01
data_official_Türkiye["Greenhouse_Agro_LandUse_km2"] = data_official_Türkiye["Greenhouse_Agro_LandUse_Decare"] * 0.001
data_official_Türkiye["LandUse_Sowed_km2"] = data_official_Türkiye["LandUse_Sowed_Hectare"] * 0.01
data_official_Türkiye["Agriculture_LandUse_Fallow_km2"] = data_official_Türkiye["Agriculture_LandUse_Fallow_Hectare"] * 0.01
data_official_Türkiye["Agriculture_LandUse_Vegetables_km2"] = data_official_Türkiye["Agriculture_LandUse_Vegetables_Hectare"] * 0.01
data_official_Türkiye["Agriculture_Longterm_Crops_km2"] = data_official_Türkiye["Agriculture_Longterm_Crops_Hectare"] * 0.01

data_official_Türkiye["Agricultural_Production_1000USD"] = (data_official_Türkiye["Agricultural_Production_1000TL"] / data_official_Türkiye["Exchange_Parity_USDTRY"])


data_official_Türkiye = data_official_Türkiye.drop(columns=["Population_Total", "Mean_Household_Size", "Landuse_Harvest_Hectare", "Greenhouse_Agro_LandUse_Decare", 
                                                            "LandUse_Sowed_Hectare", "Agriculture_LandUse_Fallow_Hectare", "Agriculture_LandUse_Vegetables_Hectare", 
                                                            "Agriculture_Longterm_Crops_Hectare", "Agricultural_Production_1000TL", "Exchange_Parity_USDTRY"])

In [20]:
data_official_Türkiye.columns

Index(['Year', 'Location_Name', 'Total_Agricultural_Production_Ton',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu  : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý)',
       'Greenhouse_Agro_Production_Ton',
       'Belediye atýk istatistikleri : Kiþi baþý ortalama belediye atýk miktarý (kg/kiþi-gün)',
       'Kullaným yerlerine göre elektrik tüketimi : Toplam (MWh)',
       'Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Belediyelerde kiþi baþý çekilen günlük su miktarý (litre/kiþi-gün)',
       'Tarýmsal üretim deðeri  : Canlý hayvanlar deðeri (1000 TL)',
       'Tarýmsal üretim deðeri  : Hayvansal ürünler deðeri (1000 TL)',
       'Water_Drainage_1000m3PerYear',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu',
       'Tarýmsal üretim deðeri  : Kiþi baþýna bitkisel üretim deðeri (TL)',
       'Waste_Collected_1000Ton',
       'Tarýmsal üretim deðeri  : Kiþi baþýna canlý hayvanlar deðeri (TL)',
       'Electric_Energy_Use_MWh', 'Water_Refined_1000m3PerYear', 'Area_km2',
       'Treated', 'Mean_Household_Count', 'Landuse_Harvest_km2',
       'Greenhouse_Agro_LandUse_km2', 'LandUse_Sowed_km2',
       'Agriculture_LandUse_Fallow_km2', 'Agriculture_LandUse_Vegetables_km2',
       'Agriculture_Longterm_Crops_km2', 'Agricultural_Production_1000USD'],
      dtype='object')

In [21]:
# Transformations on Food Sovereignty, for each location, Per Household and Per Area metrics
# Create data for processing


# data_official_Türkiye["Mean_Household_Count"]
# data_official_Türkiye["Area_km2"]



# Market
data_official_Türkiye["agro_prod_1000USD_perArea"] = data_official_Türkiye["Agricultural_Production_1000USD"] / data_official_Türkiye["Area_km2"]

data_official_Türkiye["agro_prod_1000USD_perHousehold"] = data_official_Türkiye["Agricultural_Production_1000USD"] / data_official_Türkiye["Mean_Household_Count"]


# Production
data_official_Türkiye["agro_greenhouse_prod_ton_perArea"] = data_official_Türkiye["Greenhouse_Agro_Production_Ton"] / data_official_Türkiye["Area_km2"]

data_official_Türkiye["agro_greenhouse_prod_ton_perHousehold"] = data_official_Türkiye["Greenhouse_Agro_Production_Ton"] / data_official_Türkiye["Mean_Household_Count"]

# Water 
data_official_Türkiye["water_drainage_perArea"] = data_official_Türkiye["Water_Drainage_1000m3PerYear"] / data_official_Türkiye["Area_km2"]
data_official_Türkiye["water_refined_perArea"] = data_official_Türkiye["Water_Refined_1000m3PerYear"] / data_official_Türkiye["Area_km2"]

data_official_Türkiye["water_drainage_perHousehold"] = data_official_Türkiye["Water_Drainage_1000m3PerYear"] / data_official_Türkiye["Mean_Household_Count"]
data_official_Türkiye["water_refined_perHHousehold"] = data_official_Türkiye["Water_Refined_1000m3PerYear"] / data_official_Türkiye["Mean_Household_Count"]

# Waste
data_official_Türkiye["wasteCollected_1000ton_perArea"] = data_official_Türkiye["Waste_Collected_1000Ton"] / data_official_Türkiye["Area_km2"]

data_official_Türkiye["wasteCollected_1000ton_perHousehold"] = data_official_Türkiye["Waste_Collected_1000Ton"] / data_official_Türkiye["Mean_Household_Count"]

# Energy
data_official_Türkiye["electricty_mwh_perArea"] = data_official_Türkiye["Electric_Energy_Use_MWh"] / data_official_Türkiye["Area_km2"]

data_official_Türkiye["electricty_mwh_perHousehold"] = data_official_Türkiye["Electric_Energy_Use_MWh"] / data_official_Türkiye["Mean_Household_Count"]



# Land Use
data_official_Türkiye["landuse_harvested_perArea"] = data_official_Türkiye["Landuse_Harvest_km2"] / data_official_Türkiye["Area_km2"]
data_official_Türkiye["landuse_longtermCrops_perArea"] = data_official_Türkiye["Agriculture_Longterm_Crops_km2"] / data_official_Türkiye["Area_km2"]
data_official_Türkiye["landuse_greenhouse_perArea"] = data_official_Türkiye["Greenhouse_Agro_LandUse_km2"] / data_official_Türkiye["Area_km2"]
data_official_Türkiye["landuse_sowed_perArea"] = data_official_Türkiye["LandUse_Sowed_km2"] / data_official_Türkiye["Area_km2"]
data_official_Türkiye["landuse_fallow_perArea"] = data_official_Türkiye["Agriculture_LandUse_Fallow_km2"] / data_official_Türkiye["Area_km2"]
data_official_Türkiye["landuse_vegetables_perArea"] = data_official_Türkiye["Agriculture_LandUse_Vegetables_km2"] / data_official_Türkiye["Area_km2"]


data_official_Türkiye["landuse_harvested_perHousehold"] = data_official_Türkiye["Landuse_Harvest_km2"] / data_official_Türkiye["Mean_Household_Count"]
data_official_Türkiye["landuse_longtermCrops_perHousehold"] = data_official_Türkiye["Agriculture_Longterm_Crops_km2"] / data_official_Türkiye["Mean_Household_Count"]
data_official_Türkiye["landuse_greenhouse_perHousehold"] = data_official_Türkiye["Greenhouse_Agro_LandUse_km2"] / data_official_Türkiye["Mean_Household_Count"]
data_official_Türkiye["landuse_sowed_perHousehold"] = data_official_Türkiye["LandUse_Sowed_km2"] / data_official_Türkiye["Mean_Household_Count"]
data_official_Türkiye["landuse_fallow_perHousehold"] = data_official_Türkiye["Agriculture_LandUse_Fallow_km2"] / data_official_Türkiye["Mean_Household_Count"]
data_official_Türkiye["landuse_vegetables_perHousehold"] = data_official_Türkiye["Agriculture_LandUse_Vegetables_km2"] / data_official_Türkiye["Mean_Household_Count"]


data_official_Türkiye = data_official_Türkiye.drop(columns=["Agriculture_LandUse_Vegetables_km2", "Agriculture_LandUse_Fallow_km2", "LandUse_Sowed_km2", "Greenhouse_Agro_LandUse_km2",
                                                            "Agriculture_Longterm_Crops_km2", "Landuse_Harvest_km2", "Electric_Energy_Use_MWh", "Waste_Collected_1000Ton", 
                                                            "Water_Refined_1000m3PerYear", "Water_Drainage_1000m3PerYear", "Greenhouse_Agro_Production_Ton", 
                                                            "Agricultural_Production_1000USD", "Mean_Household_Count", "Area_km2"])


data_official_Türkiye.columns

Index(['Year', 'Location_Name', 'Total_Agricultural_Production_Ton',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu  : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý)',
       'Belediye atýk istatistikleri : Kiþi baþý ortalama belediye atýk miktarý (kg/kiþi-gün)',
       'Kullaným yerlerine göre elektrik tüketimi : Toplam (MWh)',
       'Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Belediyelerde kiþi baþý çekilen günlük su miktarý (litre/kiþi-gün)',
       'Tarýmsal üretim deðeri  : Canlý hayvanlar deðeri (1000 TL)',
       'Tarýmsal üretim deðeri  : Hayvansal ürünler deðeri (1000 TL)',
       'Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu',
       'Tarýmsal üretim deðeri  : Kiþi baþýna bitkisel üretim deðeri (TL)',
       'Tarýmsal üretim deðeri  : Kiþi baþýna canlý hayvanlar deðeri (TL)',
       'Treated', 'agro_prod_1000USD_perArea',
       'agro_prod_1000USD_perHousehold', 'agro_greenhouse_prod_ton_perArea',
       'agro_greenhouse_prod_ton_perHousehold', 'water_drainage_perArea',
       'water_refined_perArea', 'water_drainage_perHousehold',
       'water_refined_perHHousehold', 'wasteCollected_1000ton_perArea',
       'wasteCollected_1000ton_perHousehold', 'electricty_mwh_perArea',
       'electricty_mwh_perHousehold', 'landuse_harvested_perArea',
       'landuse_longtermCrops_perArea', 'landuse_greenhouse_perArea',
       'landuse_sowed_perArea', 'landuse_fallow_perArea',
       'landuse_vegetables_perArea', 'landuse_harvested_perHousehold',
       'landuse_longtermCrops_perHousehold', 'landuse_greenhouse_perHousehold',
       'landuse_sowed_perHousehold', 'landuse_fallow_perHousehold',
       'landuse_vegetables_perHousehold'],
      dtype='object')

In [22]:
data_official_Türkiye.head(40)

#Notice that there is 3km2 difference from HGM, because the reference has told that this values are representative. 
# https://www.harita.gov.tr/il-ve-ilce-yuzolcumleri

,Year,Location_Name,Total_Agricultural_Production_Ton,Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý),Belediye atýk istatistikleri : Kiþi baþý ortalama belediye atýk miktarý (kg/kiþi-gün),Kullaným yerlerine göre elektrik tüketimi : Toplam (MWh),Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Belediyelerde kiþi baþý çekilen günlük su miktarý (litre/kiþi-gün),Tarýmsal üretim deðeri : Canlý hayvanlar deðeri (1000 TL),Tarýmsal üretim deðeri : Hayvansal ürünler deðeri (1000 TL),Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu,...,landuse_greenhouse_perArea,landuse_sowed_perArea,landuse_fallow_perArea,landuse_vegetables_perArea,landuse_harvested_perHousehold,landuse_longtermCrops_perHousehold,landuse_greenhouse_perHousehold,landuse_sowed_perHousehold,landuse_fallow_perHousehold,landuse_vegetables_perHousehold
0,2008,Türkiye,74382684.0,93.0,"1,15",161947528.0,215.0,25521071.0,23816982.0,17905377,...,0.000695,0.211018,0.054602,0.010715,0.008681,0.001650,3.032327e-05,0.009206,2.382194e-03,0.000467
1,2010,Türkiye,90579900.0,96.0,"1,14",172050628.0,216.0,46873045.0,38128120.0,17500632,...,0.000723,0.209387,0.054472,0.010276,0.008370,0.001552,2.906094e-05,0.008419,2.190131e-03,0.000413
2,2012,Türkiye,92921409.0,98.0,"1,12",194923349.0,216.0,63546623.0,49321861.0,17178953,...,0.000792,0.198238,0.054948,0.010599,0.007773,0.001566,3.022334e-05,0.007565,2.096953e-03,0.000404
3,2014,Türkiye,99443102.0,101.0,"1,08",207375078.0,203.0,62512147.0,44332506.0,6409722,...,0.000825,0.202321,0.052659,0.010302,0.007440,0.001503,2.981356e-05,0.007312,1.903244e-03,0.000372
4,2016,Türkiye,110785755.0,104.0,"1,17",231203746.0,217.0,89865606.0,62166678.0,6143123,...,0.000887,0.199665,0.051258,0.010309,0.006969,0.001460,3.033312e-05,0.006830,1.753312e-03,0.000353
5,2018,Türkiye,115048445.0,107.0,"1,16",258232177.0,224.0,146184051.0,79150212.0,6337385,...,0.000990,0.197701,0.045033,0.010046,0.006544,0.001433,3.201201e-05,0.006394,1.456447e-03,0.000325
6,2020,Türkiye,131927312.0,109.0,"1,13",262702129.0,228.0,195238955.0,108598173.0,5878321,...,0.001032,0.200355,0.040681,0.009990,0.006382,0.001405,3.177713e-05,0.006168,1.252384e-03,0.000308
7,2022,Türkiye,137422726.0,111.0,"1,03",286576318.0,229.0,NaN,NaN,5666274,...,0.001040,0.211897,0.037941,0.009201,0.006431,0.001378,3.042725e-05,0.006202,1.110535e-03,0.000269
8,2024,Türkiye,141261544.0,111.0,"1,09",NaN,NaN,NaN,NaN,5657686,...,0.000995,0.215660,0.034042,0.009495,0.006239,0.001375,2.808548e-05,0.006088,9.609351e-04,0.000268
9,2008,İstanbul,313740.0,2444.0,"1,15",30008801.0,147.0,191691.0,314433.0,128123,...,0.000268,0.125235,0.000000,0.007015,0.000205,0.000007,4.375465e-07,0.000205,0.000000e+00,0.000011
10,2010,İstanbul,242510.0,2551.0,"1,2",30525034.0,195.0,320958.0,267096.0,135089,...,0.000194,0.117178,0.000198,0.007081,0.000183,0.000008,3.032963e-07,0.000183,3.096030e-07,0.000011
11,2012,İstanbul,317338.0,2666.0,"1,13",33084858.0,186.0,369562.0,139953.0,144228,...,0.000260,0.118387,0.000912,0.006795,0.000168,0.000007,3.694909e-07,0.000168,1.293998e-06,0.000010
12,2014,İstanbul,290051.0,2767.0,"1,16",34964209.0,181.0,289491.0,236599.0,0,...,0.000284,0.120123,0.000313,0.006244,0.000160,0.000006,3.780687e-07,0.000160,4.162894e-07,0.000008
13,2016,İstanbul,292705.0,2849.0,"1,3",36151547.0,189.0,522913.0,275137.0,0,...,0.000291,0.122842,0.000297,0.005429,0.000159,0.000006,3.761454e-07,0.000159,3.830016e-07,0.000007
14,2018,İstanbul,300315.0,2900.0,"1,28",40425643.0,189.0,884883.0,326181.0,0,...,0.000293,0.121703,0.000286,0.005378,0.000150,0.000006,3.610366e-07,0.000150,3.520107e-07,0.000007
15,2020,İstanbul,302899.0,2976.0,"1,23",39263120.0,190.0,1192944.0,483196.0,0,...,0.000328,0.124133,0.001119,0.005255,0.000145,0.000006,3.824490e-07,0.000145,1.303998e-06,0.000006
16,2022,İstanbul,327349.0,3062.0,"1,13",42602610.0,190.0,NaN,NaN,0,...,0.000350,0.129273,0.001091,0.005129,0.000142,0.000006,3.850150e-07,0.000142,1.198897e-06,0.000006
17,2024,İstanbul,286601.0,2934.0,"1,23",NaN,NaN,NaN,NaN,0,...,0.000387,0.125325,0.001511,0.004732,0.000135,0.000005,4.175689e-07,0.000135,1.628815e-06,0.000005
18,2008,Tekirdağ,1433099.0,122.0,"1,63",4829830.0,191.0,351713.0,288868.0,249218,...,0.000017,0.564898,0.000000,0.011620,0.015878,0.000420,4.722538e-07,0.015878,0.000000e+00,0.000327
19,2010,Tekirdağ,1310936.0,126.0,"1,47",5326923.0,176.0,576582.0,401178.0,252628,...,0.000030,0.556829,0.000124,0.009425,0.015115,0.000432,8.244488e-07,0.015115,3.376732e-06,0.000256
20,2012,Tekirdağ,1515914.0,135.0,"1,43",5838473.0,156.0,780334.0,231445.0,263272,...,0.000034,0.497532,0.000113,0.008582,0.012076,0.000371,8.130739e-07,0.011924,2.710246e-06,0.000206
21,2014,Tekirdağ,1663033.0,144.0,"1,2",6366016.0,140.0,789051.0,318471.0,0,...,0.000042,0.540493,0.000192,0.008263,0.012292,0.000359,9.426159e-07,0.012176,4.330938e-06,0.000186
22,2016,Tekirdağ,1823541.0,154.0,"1,37",8302423.0,176.0,952870.0,278295.0,0,...,0.000048,0.622409,0.000058,0.007189,0.012808,0.000358,9.768984e-07,0.012672,1.184119e-06,0.000146
23,2018,Tekirdağ,1589742.0,163.0,"1,33",7977933.0,186.0,1359001.0,383448.0,0,...,0.000052,0.617480,0.000000,0.005502,0.011968,0.000357,9.911382e-07,0.011876,0.000000e+00,0.000106
24,2020,Tekirdağ,1799424.0,171.0,"1,15",7607210.0,203.0,1619824.0,548847.0,0,...,0.000051,0.611029,0.000000,0.004809,0.010974,0.000332,9.004084e-07,0.010846,0.000000e+00,0.000085
25,2022,Tekirdağ,1767989.0,181.0,"1,16",8308983.0,217.0,NaN,NaN,0,...,0.000053,0.647417,0.000000,0.004756,0.011007,0.000316,8.900163e-07,0.010874,0.000000e+00,0.000080
26,2024,Tekirdağ,1685914.0,191.0,"1,19",NaN,NaN,NaN,NaN,0,...,0.000053,0.647922,0.012732,0.004045,0.010246,0.000297,8.313945e-07,0.010135,1.991556e-04,0.000063
27,2008,Edirne,1642778.0,65.0,"1,81",862269.0,155.0,366008.0,284552.0,132605,...,0.000013,0.546685,0.000000,0.018072,0.027240,0.000271,6.486859e-07,0.027240,0.000000e+00,0.000900
28,2010,Edirne,1797556.0,64.0,"1,84",1001818.0,172.0,549934.0,343697.0,128508,...,0.000014,0.567564,0.000181,0.015180,0.027686,0.000274,6.749004e-07,0.027692,8.813405e-06,0.000741
29,2012,Edirne,1614394.0,66.0,"2,01",1081594.0,197.0,677210.0,240640.0,123129,...,0.000012,0.470055,0.000252,0.013844,0.022107,0.000343,5.704164e-07,0.021680,1.163349e-05,0.000638
30,2014,Edirne,1742789.0,66.0,"1,81",1056059.0,190.0,687893.0,308582.0,116435,...,0.000015,0.488721,0.001064,0.011098,0.022120,0.000418,6.592885e-07,0.021758,4.738183e-05,0.000494
31,2016,Edirne,1685637.0,66.0,"1,59",1078745.0,212.0,951603.0,313621.0,110978,...,0.000016,0.500285,0.001050,0.009364,0.022761,0.000425,6.930528e-07,0.022194,4.656448e-05,0.000415
32,2018,Edirne,1665229.0,68.0,"1,33",1183017.0,214.0,1150214.0,415348.0,111330,...,0.000014,0.493292,0.001032,0.009325,0.021064,0.000299,6.055481e-07,0.020625,4.313680e-05,0.000390
33,2020,Edirne,1731198.0,67.0,"1,33",1214848.0,223.0,1633461.0,622988.0,105876,...,0.000014,0.489175,0.001107,0.008166,0.020307,0.000288,5.495839e-07,0.019904,4.502615e-05,0.000332
34,2022,Edirne,1842876.0,68.0,"1,23",1269686.0,242.0,NaN,NaN,101153,...,0.000012,0.537972,0.001098,0.006640,0.021139,0.000352,4.513954e-07,0.020726,4.231832e-05,0.000256
35,2024,Edirne,1683221.0,69.0,"1,19",NaN,NaN,NaN,NaN,99079,...,0.000014,0.551974,0.000687,0.006304,0.021305,0.000385,5.308050e-07,0.020935,2.604648e-05,0.000239
36,2008,Kırklareli,1024798.0,54.0,"1,43",1680453.0,258.0,284450.0,194612.0,118871,...,0.000007,0.353223,0.001606,0.006277,0.021653,0.000134,4.463676e-07,0.021668,9.848579e-05,0.000385
37,2010,Kırklareli,933720.0,53.0,"1,49",1574076.0,185.0,445854.0,320835.0,113458,...,0.000007,0.349446,0.001745,0.005810,0.021025,0.000165,4.005517e-07,0.021025,1.049818e-04,0.000350
38,2012,Kırklareli,1050152.0,54.0,"0,87",1871880.0,183.0,821558.0,283592.0,109064,...,0.000013,0.270625,0.016828,0.005626,0.016034,0.000186,7.473228e-07,0.015368,9.556061e-04,0.000320
39,2014,Kırklareli,1288133.0,55.0,"1,3",2065081.0,148.0,812000.0,297893.0,107221,...,0.000010,0.340876,0.003496,0.004002,0.019653,0.000199,5.411334e-07,0.019217,1.970773e-04,0.000226

In [23]:
data_official_Türkiye.dtypes

Year                                                                                                                                               int64
Location_Name                                                                                                                             string[python]
Total_Agricultural_Production_Ton                                                                                                                float64
Adrese Dayalý Nüfus Kayýt Sistemine göre nüfus yoðunluðu  : Nüfus yoðunluðu (kilometrekareye düþen kiþi sayýsý)                                  float64
Belediye atýk istatistikleri : Kiþi baþý ortalama belediye atýk miktarý (kg/kiþi-gün)                                                     string[python]
Kullaným yerlerine göre elektrik tüketimi : Toplam (MWh)                                                                                         float64
Ýçme ve kullanma suyu þebekesi ve arýtma tesisleri : Belediyelerde kiþi baþý çekilen günlük su miktarý (litre/kiþi-gün)                          float64
Tarýmsal üretim deðeri  : Canlý hayvanlar deðeri (1000 TL)                                                                                       float64
Tarýmsal üretim deðeri  : Hayvansal ürünler deðeri (1000 TL)                                                                                     float64
Adrese Dayalý Nüfus Kayýt Sistemine göre il ve ilçe merkezleri ile belde ve köyler nüfusu ve nüfus artýþ hýzý : Belde ve köyler nüfusu    string[python]
Tarýmsal üretim deðeri  : Kiþi baþýna bitkisel üretim deðeri (TL)                                                                                float64
Tarýmsal üretim deðeri  : Kiþi baþýna canlý hayvanlar deðeri (TL)                                                                                float64
Treated                                                                                                                                            int32
agro_prod_1000USD_perArea                                                                                                                        float64
agro_prod_1000USD_perHousehold                                                                                                                   float64
agro_greenhouse_prod_ton_perArea                                                                                                                 float64
agro_greenhouse_prod_ton_perHousehold                                                                                                            float64
water_drainage_perArea                                                                                                                           float64
water_refined_perArea                                                                                                                            float64
water_drainage_perHousehold                                                                                                                      float64
water_refined_perHHousehold                                                                                                                      float64
wasteCollected_1000ton_perArea                                                                                                                   float64
wasteCollected_1000ton_perHousehold                                                                                                              float64
electricty_mwh_perArea                                                                                                                           float64
electricty_mwh_perHousehold                                                                                                                      float64
landuse_harvested_perArea                                                                                                                        float64
landuse_longtermCrops_perArea                                                                                                                    float64
landuse_greenhouse_perArea                                                                                                                       float64
landuse_sowed_perArea                                                                                                                            float64
landuse_fallow_perArea                                                                                                                           float64
landuse_vegetables_perArea                                                                                                                       float64
landuse_harvested_perHousehold                                                                                                                   float64
landuse_longtermCrops_perHousehold                                                                                                               float64
landuse_greenhouse_perHousehold                                                                                                                  float64
landuse_sowed_perHousehold                                                                                                                       float64
landuse_fallow_perHousehold                                                                                                                      float64
landuse_vegetables_perHousehold                                                                                                                  float64
dtype: object

## Food Sovereignty Index